
name: Ekstraklasa no-draw streak to Telegram

on:
  schedule:
    - cron: "*/100 * * * *"  # co 30 minut (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run streak checker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          THRESHOLD: ${{ secrets.THRESHOLD }}
          ALERT_MODE: ${{ secrets.ALERT_MODE }}
        run: python ekstra_streak_bot.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json
            git commit -m "chore: update streak state"
            git push
          fi
